src = ["/workspaces/bookfinder/backend/"]

lint.select = ["ALL"] # Use very strict style checking
lint.ignore = [
    "D211", "D213", "TD", # Ignore conflicting rules
    "TD", # Ignore overly strict rules
    "COM", # Should not be used alongside the formatter
    "D203", # Incompatible with formatter
    "D202", # No blank lines allowed after function docstring
    "FIX002", # Find TODOs in code -> TODO remove this ignore later
    "D103", # Missing docstring in public function -> TODO remove later and check if it makes sense per case
    "D100", # Missing docstring in public module -> TODO remove later and check if it makes sense per case
    "D205", # 1 blank line required between summary line and description (see geo_utils.py) -> TODO remove later and check if it makes sense per case. Can probably also stay ignored.
    "S104", # Possible binding to all interfaces 0.0.0.0 -> TODO remove ignore when in production
    "S201", # Use of `debug=True` in Flask app detected -> TODO remove ignore when in production
    "G004", # Logging statement uses f-string
    "BLE001", # Do not catch blind exception: `Exception` -> TODO remove from ignored
    "TRY400" # Use `logging.exception` instead of `logging.error` -> TODO remove from ignored
]

[lint.per-file-ignores]
"*_test.py" = [
    "S101", # Allow asserts in test files
    "PLR2004", # Magic value used in comparison
    "F811" # Allow fixtures
]
"catalog_api_test_utils.py" = [
    "S101", # Allow asserts in test files
]
"reset_bookshelves.py" = [
    "T201" # Allow print statements
]
"fuzzysearch_cli.py" = [
    "T201" # Allow print statements
]
