from flask import Request, jsonify
from flask.typing import ResponseReturnValue
from http_constants.status import HttpStatus

from app.db.book_db import get_book_from_database, save_book_to_db
from app.db.database_utils import check_if_shelf_exists
from app.db.shelf_db import (
    get_books_in_shelf_from_db,
    get_shelf_metadata_from_db,
    insert_book_to_shelf_in_db,
    remove_book_from_shelf_in_db,
)
from app.models.identifiers import Isbn, OsmId
from app.routes.books import get_book
from app.utils.naming import as_json_dict

logger = __import__("logging").getLogger(__name__)


def get_shelf_metadata(request: Request) -> ResponseReturnValue:
    """Fetch metadata of the given shelf.

    Request parameters:
    - osm_id: OSM ID of the shelf (required)
    """

    osm_id = OsmId.parse(request.args.get("osm_id"))
    if not osm_id:
        return jsonify(
            {"status": "error", "message": "osm_id missing or invalid"}
        ), HttpStatus.BAD_REQUEST.value

    shelf = get_shelf_metadata_from_db(osm_id)
    if not shelf:
        return jsonify(
            {"status": "error", "message": "Shelf not found"}
        ), HttpStatus.NOT_FOUND.value

    return jsonify(
        {"status": "success", "data": as_json_dict(shelf)}
    ), HttpStatus.OK.value


def get_books_in_shelf(request: Request) -> ResponseReturnValue:
    """Fetch all books from the given shelf.

    Request parameters:
    - osm_id: OSM ID of the shelf (required)
    """

    osm_id = OsmId.parse(request.args.get("osm_id"))
    if not osm_id:
        return jsonify(
            {"status": "error", "message": "osm_id missing or invalid"}
        ), HttpStatus.BAD_REQUEST.value

    books = get_books_in_shelf_from_db(osm_id)
    return jsonify(
        {"status": "success", "data": [as_json_dict(book) for book in books]}
    ), HttpStatus.OK.value


def insert_book_to_shelf(request: Request) -> ResponseReturnValue:
    """Insert a book into the given shelf.

    Request body (JSON):
    - osm_id: OSM ID of the shelf (required)
    - isbn: ISBN of the book to insert (required)
    """

    # TODO: Update total_insertions in db when a book is inserted into a shelf

    data = request.get_json(silent=True) or {}
    osm_id = OsmId.parse(data.get("osm_id"))
    isbn = Isbn.parse(data.get("isbn"))

    # TODO: remove this error!
    if str(isbn) == "978-1-4454-0479-0":
        logger.error("Simulating error for testing frontend error handling")
        return jsonify(
            {
                "status": "error",
                "message": "Simulated error for testing frontend error handling",
            }
        ), HttpStatus.BAD_REQUEST.value

    if not osm_id:
        return jsonify(
            {"status": "error", "message": "osm_id not provided or invalid"}
        ), HttpStatus.BAD_REQUEST.value

    if not isbn:
        return jsonify(
            {"status": "error", "message": "isbn not provided or invalid"}
        ), HttpStatus.BAD_REQUEST.value

    if not check_if_shelf_exists(osm_id):
        return jsonify(
            {
                "status": "error",
                "message": f"Shelf with OSM ID {osm_id} does not exist.",
            }
        ), HttpStatus.NOT_FOUND.value

    if not get_book_from_database(isbn):
        book = get_book(isbn)
        if not book:
            return jsonify(
                {"status": "error", "message": "Book metadata not found"}
            ), HttpStatus.NOT_FOUND.value

        save_book_to_db(book)

    insert_book_to_shelf_in_db(
        osm_id, isbn
    )  # TODO: get a return value for success/failure -> similar to remove fn
    # TODO: Only return success if book was actually inserted successfully

    return jsonify(
        # TODO: Message should be generated by frontend from the 200 code
        {"status": "success", "message": f"Book {isbn} inserted into shelf {osm_id}."}
    ), HttpStatus.OK.value


def remove_book_from_shelf(request: Request) -> ResponseReturnValue:
    """Remove a book entity from the given shelf.

    Request body (JSON):
    - osm_id: OSM ID of the shelf (required)
    - isbn: ISBN of the book to remove (required)
    """

    # TODO: Update avg_days_until_takeout in db when a book is taken out of a shelf

    data = request.get_json(silent=True) or {}
    osm_id = OsmId.parse(data.get("osm_id"))
    isbn = Isbn.parse(data.get("isbn"))

    if not osm_id:
        return jsonify(
            {"status": "error", "message": "osm_id not provided or invalid"}
        ), HttpStatus.BAD_REQUEST.value

    if not isbn:
        return jsonify(
            {"status": "error", "message": "isbn not provided or invalid"}
        ), HttpStatus.BAD_REQUEST.value

    error = remove_book_from_shelf_in_db(osm_id, isbn)

    if not error:
        return jsonify(
            {
                "status": "success",
                "message": f"Book {isbn} removed from shelf {osm_id}.",
            }
        ), HttpStatus.OK.value

    return jsonify(
        {
            "status": "error",
            "message": error.message,
        }
    ), HttpStatus.NOT_FOUND.value
