from flask import Request, jsonify
from flask.typing import ResponseReturnValue

from app.db.book_db import save_book_to_db
from app.db.shelf_db import (
    check_if_book_in_shelf,
    get_books_in_shelf_from_db,
    get_shelf_metadata_from_db,
    insert_book_to_shelf_in_db,
    remove_book_from_shelf_in_db,
)
from app.models.book import Book
from app.models.identifiers import Isbn, OsmId
from app.routes.books import get_book
from app.utils.naming import as_json_dict


def get_shelf_metadata(request: Request) -> ResponseReturnValue:
    """Fetch metadata of the given shelf."""
    # TODO: Move api logic from db/shelf_db.py to here
    osm_id = OsmId.parse(request.args.get("osm_id"))
    if not osm_id:
        return jsonify({"status": "error", "message": "osm_id is required"}), 400
    shelf = get_shelf_metadata_from_db(osm_id)
    if not shelf:
        return jsonify({"status": "error", "message": "Shelf not found"}), 404
    return jsonify(as_json_dict(shelf))


def get_books_in_shelf(request: Request) -> ResponseReturnValue:
    """Fetch all books from the given shelf."""
    # TODO: Move api logic from db/shelf_db.py to here
    return get_books_in_shelf_from_db(request)


def check_if_shelf_exists(osm_id: OsmId) -> bool:
    """Check if a shelf with the given osm_id exists in the database."""
    return get_shelf_metadata_from_db(osm_id) is not None


def insert_book_to_shelf(request: Request) -> ResponseReturnValue:
    """Insert a book into the given shelf."""
    # TODO: Use function from utils to normalize ISBN / check if the db function
    #       uses it already
    data = request.json
    osm_id = OsmId.parse(data.get("osm_id"))
    isbn = Isbn.parse(data.get("isbn"))

    if not osm_id:
        return jsonify(
            {"status": "error", "message": "osm_id not provided or invalid"}
        ), 400

    if not isbn:
        return jsonify(
            {"status": "error", "message": "isbn not provided or invalid"}
        ), 400

    if not check_if_shelf_exists(osm_id):
        return jsonify(
            {
                "status": "error",
                "message": f"Shelf with osm_id {osm_id} does not exist.",
            }
        ), 404

    if not check_if_book_in_shelf(osm_id, isbn):
        book = get_book(isbn)
        if not book:
            return jsonify(
                {"status": "error", "message": "Book metadata not found"}
            ), 404
        save_book_to_db(book)

    insert_book_to_shelf_in_db(
        osm_id, isbn
    )  # todo: get a return value for success/failure
    # TODO: Only return success if book was actually inserted successfully
    return jsonify(
        # TODO: Message should be generated by frontend from the 200 code
        # TODO: dont send status in body, only use http status code?
        {"status": "success", "message": f"Book {isbn} inserted to shelf {osm_id}."}
    )


def remove_book_from_shelf(request: Request) -> ResponseReturnValue:
    """Remove a book from the given shelf."""
    # TODO: Use function from utils to normalize ISBN / check if the db function
    #       uses it already
    data = request.json
    osm_id = OsmId.parse(data.get("osm_id"))
    isbn = Isbn.parse(data.get("isbn"))
    if not osm_id:
        return jsonify(
            {"status": "error", "message": "osm_id not provided or invalid"}
        ), 400
    if not isbn:
        return jsonify(
            {"status": "error", "message": "isbn not provided or invalid"}
        ), 400
    # TODO: check if shelf and book exist
    remove_book_from_shelf_in_db(osm_id, isbn)  # todo check if successful
    # TODO: Only return success if book was actually removed successfully
    return jsonify(
        {"status": "success", "message": f"Book {isbn} removed from shelf {osm_id}."}
    )
